name: Otus hw 12 chain of responsibilities

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install "poetry==${{ vars.POETRY_VERSION }}"
          python -m pip install --upgrade pip
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          pip install -r requirements.txt
      - name: Run tests
        run: pytest

  send_success_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!

  send_failure_message:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ failure() }}
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} тесты не прошли!
